Repository gisce/openerp-client-kde, pull requests merged in 2018-04, with the labels that each got.

#2 Fix conflict with qgis
  .gitignore
  Koo/Fields/Selection/Selection.py
Labels: bug

#3 Fix kooApi inheritance
  Koo/Common/Api.py
Labels: bug

#12 Fixes binary field
  Koo/Fields/Binary/BinaryFieldWidget.py
  Koo/Fields/Image/ImageFieldWidget.py
  Koo/Model/Field.py
Labels: enhancement, to be merged

#13 Enables the interpretation of the attrs values
  Koo/Model/Record.py
Labels: enhancement, to be merged

#10 Fix *2many
  Koo/Model/Field.py
  Koo/Model/Group.py
Labels: enhancement, to be merged

#17 Fix selection widget
  Koo/Fields/Selection/Selection.py
Labels: bug, enhancement

#18 Avoid using reserved word
  Koo/Fields/Selection/Selection.py
Labels: enhancement

#21 Signals disconnection
  Koo/Dialogs/FormWidget.py
  Koo/Model/Field.py
  Koo/Model/Field_rolf.py
  Koo/Model/Group.py
  Koo/Model/KooModel.py
  Koo/Model/Record.py
Labels: bug, enhancement

#24 Fixes save binary field
  Koo/Fields/Binary/BinaryFieldWidget.py
Labels: bug

#26 Improve Abstract Field Widget docstrings
  Koo/Fields/AbstractFieldWidget.py
Labels: documentation, enhancement

#29 Fix identation
  tests/test_show_qt5_window.py
Labels: enhancement
