Repository gisce/openerp-client-kde, pull requests merged in 2018-10, with the labels that each got.

#129 Sort list of default fields to ensure XML is repeatable
  Koo/Model/Record.py
Labels: to be merged

#118 Improve wizard code
  Koo/Actions/Wizard.py
Labels: enhancement, to be merged

#117 Improve code of actions
  Koo/Actions/Actions.py
Labels: enhancement, to be merged

#119 Improve arrows code
  Koo/Common/ArrowsEventFilter.py
Labels: enhancement, to be merged

#113 Fix many2one completer
  Koo/Fields/ManyToOne/ManyToOne.py
Labels: bug, to be merged

#120 Improve code command line
  Koo/Common/CommandLine.py
Labels: enhancement, to be merged

#131 Fixes the set of the many2one when is numeric data
  Koo/Fields/ManyToOne/ManyToOne.py
Labels: bug, to be merged

#128 Fix the search of reference field
  Koo/Fields/Reference/ReferenceFieldWidget.py
Labels: bug, to be merged

#108 Fix the expression comparsion
  Koo/Rpc/Rpc.py
Labels: bug, to be merged

#133 Fix the load of one2may fields
  Koo/Screen/Action.py
Labels: bug
